name: API Response Demo

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Arbitrary data passed in'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate JSON output
      run: |
        cat <<EOF > result.json
        {
          "status": "ok",
          "received": "${{ github.event.inputs.payload }}"
        }
        EOF

    - uses: actions/upload-artifact@v4
      with:
        name: api-response
        path: result.json
